# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5b044355553d49512a480618bbbab6df0c629998bcaaeec3626e35ab65ba30c4a7bd9dab7214d5032ab7510fcfca36e56fbe557addd9ffb43688320ce37c3ff3

test:
  secret_key_base: 786bf22adeda5c17c48ee22f049077cd8497ace27dae8df5cfceabcb698592735d15fc465522c4f14cc8da31fc5409cf2ecaf532e19523843e55e7f8d7772eea

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
